openapi: 3.0.0
info:
  title: Wariozone
  description: The API specification for the Wariozone game
  version: 1.0.0
servers:
  - url: wariozone.web.app
    description: Production server

paths:
  /wariozone:
    get:
      tags:
        - Feed
      summary: Get all Wariozone events
      description: This endpoint returns the entire log of events from the game
      responses:
        200:
          $ref: "#/components/responses/WariozoneEventResponse"
  /stats:
    get:
      tags:
        - General
      summary: Get your stats
      description: This endpoint returns the stats of the player
      security:
        - bearer: []
      responses:
        200:
          $ref: "#/components/responses/Player"
  /prices:
    get:
      tags:
        - General
      summary: Get the prices of all items
      description: This endpoint returns a list of all prices for items in the game
      responses:
        200:
          $ref: "#/components/responses/Prices"
  /rules:
    get:
      tags:
        - General
      summary: Get the game rules
      description: This endpoint returns the rules of the game
      responses:
        200:
          $ref: "#/components/responses/Rules"
  /register:
    post:
      tags: 
        - Setup
      summary: Register group
      description: This endpoint is used to register your group to the game.
      requestBody:
        description: Register a new group to the game.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Group"
      responses: 
        200:
          description: Successfully registered.
          content: 
           application/json:
            schema: 
              $ref: "#/components/schemas/RegisterResponse"
        400:
          description: Invalid request. See response for details. 
        403:
          $ref: "#/components/responses/Conflict"
  /players:
    get:
      tags:
        - Setup
      summary: Get all players
      description: This endpoint returns a list of the game's participating players
      responses:
        200:
          $ref: "#/components/responses/PlayersResponse"
    post:
      tags:
        - Setup
      summary: Join the Wariozone game
      description: This enters the group to the game and opens for use of other endpoints. Before calling this endpoint you cannot participate in the game. 
      security:
        - bearer: []
      responses:
        200:
          $ref: "#/components/responses/Message"
        400:
          $ref: "#/components/responses/InvalidRequest"
        404:
          $ref: "#/components/responses/NotFound"
        403:
          $ref: "#/components/responses/Forbidden"
  /coins:
    get:
      tags:
        - Actions
      summary: Request coins
      description: This endpoint gives you coins.
      security:
        - bearer: []
      responses:
        200:
          $ref: "#/components/responses/Message"
        400:
          $ref: "#/components/responses/InvalidRequest"
        404:
          $ref: "#/components/responses/NotFound"
        403:
          $ref: "#/components/responses/Forbidden"
  /star:
    get:
      tags:
        - Actions
      summary: Buy star
      description: This endpoint can be used to buy stars with your coins
      security:
        - bearer: []
      responses:
        200:
          $ref: "#/components/responses/Message"
        400:
          $ref: "#/components/responses/InvalidRequest"
        404:
          $ref: "#/components/responses/NotFound"
        403:
          $ref: "#/components/responses/Forbidden"
  /mushroom:
    get:
      tags:
        - Actions
      summary: Buy mushroom
      description: This endpoint can be used to buy mushrooms with your coins
      security:
        - bearer: []
      responses:
        200:
          $ref: "#/components/responses/Message"
        400:
          $ref: "#/components/responses/InvalidRequest"
        404:
          $ref: "#/components/responses/NotFound"
        403:
          $ref: "#/components/responses/Forbidden"
    post:
      tags:
        - Actions
      summary: Use mushroom
      description: This endpoint can be used to apply mushroom and restore some health
      security:
        - bearer: []
      responses:
        200:
          $ref: "#/components/responses/Message"
        400:
          $ref: "#/components/responses/InvalidRequest"
        404:
          $ref: "#/components/responses/NotFound"
        403:
          $ref: "#/components/responses/Forbidden"
  /boomerang:
    get:
      tags:
        - Actions
      summary: Buy boomerangs
      description: This endpoint can be used to buy boomerangs
      security:
        - bearer: []
      responses:
        200:
          $ref: "#/components/responses/Message"
        400:
          $ref: "#/components/responses/InvalidRequest"
        404:
          $ref: "#/components/responses/NotFound"
        403:
          $ref: "#/components/responses/Forbidden"
    post:
      tags:
        - Actions
      summary: Throw a boomerang
      description: This endpoint can be used to throw a boomerang at another group, with a 50% chance of hitting yourself instead
      security:
        - bearer: []
      parameters:
        - in: query
          name: target
          example: "QefIx9EZp6G57DCC8eiV"
          description: The ID of the group you want to target
          schema:
            $ref: "#/components/schemas/Target"
          required: true
      responses:
        200:
          $ref: "#/components/responses/Throw"
        400:
          $ref: "#/components/responses/InvalidRequest"
        404:
          $ref: "#/components/responses/NotFound"
        403:
          $ref: "#/components/responses/Forbidden"
  /shell:
    get:
      tags:
        - Actions
      summary: Buy shells
      description: This endpoint can be used to buy shells
      security:
        - bearer: []
      responses:
        200:
          $ref: "#/components/responses/Message"
        400:
          $ref: "#/components/responses/InvalidRequest"
        404:
          $ref: "#/components/responses/NotFound"
        403:
          $ref: "#/components/responses/Forbidden"
    post:
      tags:
        - Actions
      summary: Throw a shell
      description: This endpoint can be used to throw shells at another group
      security:
        - bearer: []
      parameters:
        - in: query
          name: target
          example: "QefIx9EZp6G57DCC8eiV"
          description: The ID of the group you want to target
          schema:
            $ref: "#/components/schemas/Target"
          required: true
      responses:
        200:
          $ref: "#/components/responses/Throw"
        400:
          $ref: "#/components/responses/InvalidRequest"
        404:
          $ref: "#/components/responses/NotFound"
        403:
          $ref: "#/components/responses/Forbidden"
  /oneup:
    post:
      tags:
        - Actions
      summary: Revive player
      description: This endpoint oneups the player to get back in the game. Used if dead.
      security:
        - bearer: []
      responses:
        200:
          $ref: "#/components/responses/Message"
        404:
          $ref: "#/components/responses/NotFound"
        403:
          $ref: "#/components/responses/Forbidden"
components:
  securitySchemes:
    bearer:
      type: apiKey
      name: Authorization
      in: header
  requestBodies:
    join:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Player"
  responses:
    Message:
      description: Successful request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    PlayersResponse:
      description: The list of players in the game
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PlayersResponse"
    WariozoneEventResponse:
      description: The list of events from the game
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/WariozoneEvent"
    Prices:
      description: The prices for items in the game
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Prices"
    Rules:
      description: The rules of the game
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Rules"
    Player:
      description: The group stats after the action is performed
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Player"
    Throw:
      description: The result of a fired shot
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    Conflict:
      description: One or more resources already exists
    InvalidRequest:
      description: Invalid request, please check the documentation
    Unauthorized:
      description: Invalid or missing token
    NotFound:
      description: Player not found in the database, may not be registered to the game session
    Forbidden:
      description: Forbidden or invalid action
  schemas:
    Message:
      type: string
      description: The message returned from the server
      example: "A message containing information about the response"
    Prices:
      type: object
      properties:
        shell:
          type: integer
          description: The shell cost
          example: 1
        boomerang:
          type: integer
          description: The boomerang cost
          example: 2
        mushroom:
          type: integer
          description: The mushroom cost
          example: 1
        star:
          type: integer
          description: The star cost
          example: 1
    Rules:
      type: object
      properties:
        description:
          type: string
          description: The game description
        initialHealth:
          type: integer
          description: The initial health of new players
        starProtection:
          type: number
          description: The reduction factor applied to a shot when using star
        initialCoins:
          type: integer
          description: The initial amount of coins
        shellDamage:
          type: integer
          description: The amount of damage a shell gives to a target
        boomerangDamage:
          type: integer
          description: The amount of damaga a boomerang gives to a targer
        boomerangRisk:
          type: integer
          description: The chance of getting hit by your own boomerang shot, given in percents
    WariozoneEventResponse:
      type: array
      items:
        $ref: "#/components/schemas/WariozoneEvent"
    WariozoneEvent:
      type: object
      properties:
        id:
          type: string
          description: The unique identificator of the event
          example: "QefIx9EZp6G57DCC8eiV"
        type:
          type: string
          description: The type of event being fired
          example: "oneup"
        source:
          type: string
          description: The group who fired the event
          example: "Group A"
        target:
          type: string
          description: The target of the event
          example: "Group B"
        message:
          type: string
          description: A message
          example: "Group A just shot Group B!"
    Target:
      type: string
      description: The unique identificator of the group to shoot at
      example: "QefIx9EZp6G57DCC8eiV"
    PlayersResponse:
      type: array
      items:
        $ref: "#/components/schemas/Player"
    Player:
      type: object
      properties:
        id:
          type: string
          description: The unique identificator of the group
          example: "QefIx9EZp6G57DCC8eiV"
        name:
          type: string
          description: Your nickname
          example: "The Geniuses"
        members:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The name of a member
                example: "Ola Nordmann"
        health:
          type: integer
          description: The current health of the group
          example: 100
        coins:
          type: integer
          description: The amount of coins
          example: 10
        shells:
          type: integer
          description: The amount of shells
          example: 1
        star:
          type: integer
          description: The amount of stars
          example: 1
        mushroom:
          type: integer
          description: The amount of mushroom
          example: 1
        boomerangs:
          type: integer
          description: The amount of boomerangs
          example: 1
        kills:
          type: integer
          description: The amount of kills
          example: 3
        deaths:
          type: integer
          description: The amount of deaths
          example: 1
        dead:
          type: boolean
          description: Dead or not dead?
          example: true
      required:
        - name
        - members
    Group:
      required: 
        - name
        - members
      type: object
      properties:
        name:
          type: string
          description: Name of the group
          example: "The Geniuses"
        members:
          type: array
          items:
            $ref: "#/components/schemas/Member"
    Member:
      required:
        - name
        - email
        - phone
      type: object
      properties:
        name:
          type: string
          description: Name of this member
          example: "Ola Nordmann"
        email:
          type: string
          description: Email of the member
          example: "ola.nordmann@email.com"
        phone:
          type: string
          description: Phonenumber of the member
          example: "12345678"
    RegisterResponse:
      type: object
      properties:
        linkToDocs:
          type: string
          description: The link to the documentation for the game. 
        token:
          type: string
          description: JWT Token to be used by group as authentication for further requests.
          example: "xxxxx.yyyyy.zzzzz"
        
